---
title: "myMonopolyQuarto"
format: html
editor: visual
---

# myMonopoly v.2

The goal of this project is to simulate Monopoly in R in order to see if Georgist rules outperform the regular rules in tax-dollars collected and in the fairness of the game (measured in how slowly the game reaches a state of monopoly).

## Game Loop

Multiple Two player games, game loop - Function

```{r}
##------------------## Two player game loop - Function ##-------------------##
multipleGamesOfMonopolyFUNC <- function(nGames){
    
    multipleGamesResult <- list()
    
    for (i in 1:nGames) {
      
      #--# Source and X11 #---#
      X11()
      source("boardGraphics.R")
      #source("gameBoardData.R")
      ##---------------------##
      
      ##------------## Clean two player input settings ##-------------##
      ownedColors <- data.frame(
          colors = c("brown", "cyan", "magenta", "orange", 
                     "red", "yellow", "green", "blue"),
          ownedBy = c(NA, NA, NA, NA, NA, NA, NA, NA)
          )
      
      houseCost <- data.frame(
      colors = c("brown", "cyan", "magenta", "orange", 
                 "red", "yellow", "green", "blue"),
      cost = c(50, 50, 100, 100, 150, 150, 200, 200)
      )
      
      framePause <- 0 #0.050 # 0.025
      n_loops <- 1
      jail <- 0 #
      
      player_A_data <- data.frame(
        "name" = "player_A",
        "money" = 1800, # 1500
        "color" = "purple1",
        "mortageStamp" = "mortaged_A",
        "position" = 1,
        "debtCounter" = 0,
        "debtorName" = "none"
      )
      
      player_B_data <- data.frame(
        "name" = "player_B",
        "money" = 1800,
        "color" = "tan",
        "mortageStamp" = "mortaged_B",
        "position" = 1,
        "debtCounter" = 0,
        "debtorName" = "none"
      )
      
      player_1 <- player_A_data
      player_2 <- player_B_data
      
      #currentPlayer <- player_1
      
       ##--------------------------## Dice Function ##-----------------------------##
dice <- function(n_dice){
  
  dice_res <- sample(1:6, n_dice)
  dice_res <- sum(dice_res)
  
  return(dice_res)
}
#----------------------------------------------------------------------------#
      
      dice_1 <- dice(2) #
      dice_2 <- dice(2) #
      
      while (dice_1 == dice_2) { #
        dice_1 <- dice(2) #
        dice_2 <- dice(2) #
      } #
      
      if (dice_1 > dice_2) { #
        currentPlayer <- player_1 #
        visited_tiles <- 0 # obs tileNr count with 1
      } else { #
        currentPlayer <- player_2 #
        visited_tiles <- 1 # obs tileNr count with 1
      } #
      
      #cat("dice 1:", dice_1)
      #cat("dice 2:", dice_2)
      #cat("currentPlayer$name", currentPlayer$name)
      
      gameOver <- 0
      
      ##-------------## Clean GameBoard - Input settings ##---------------##
      gameBoard <- data.frame(
      "tileNr"          = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
                            11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 
                            21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 
                            31, 32, 33, 34, 35, 36, 37, 38, 39, 40), 
      "tileType"        = c("GO", "brown", "CC", "brown", "I", 
                            "T1", "cyan", "?", "cyan", "cyan",
                            "JAIL", "magenta", "E", "magenta", "magenta",
                            "T2", "orange", "CC", "orange", "orange",
                            "P", "red", "?", "red", "red", 
                            "T3", "yellow", "yellow", "W", "yellow",
                            "GT_J", "green", "green", "CC", "green",
                            "T4", "?", "blue", "S", "blue"),
      "ownedBy"         = c("!", "none", "!", "none", "!", 
                            "none", "none", "!", "none", "none",
                            "!", "none", "none", "none", "none", 
                            "none", "none", "!", "none", "none",
                            "!", "none", "!", "none", "none", 
                            "none", "none", "none", "none", "none",
                            "!", "none", "none", "!", "none", 
                            "none", "!", "none", "!", "none"),
      "propPlayer"      = c("!", "0", "!", "0", "!", 
                            "T", "0", "!", "0", "0",
                            "!", "0", "U", "0", "0", 
                            "T", "0", "!", "0", "0",
                            "!", "0", "!", "0", "0", 
                            "T", "0", "0", "U", "0",
                            "!", "0", "0", "!", "0", 
                            "T", "!", "0", "!", "0"),
      "tileCost"        = c(1e6, 60, 1e6, 60, 1e6,
                            200, 100, 1e6, 100, 120,
                            1e6, 140, 150, 140, 160,
                            200, 180, 1e6, 180, 200,
                            1e6, 220, 1e6, 220, 240,
                            200, 260, 260, 150, 280,
                            1e6, 300, 300, 1e6, 320,
                            200, 1e6, 350, 1e6, 400),
      "tileRent"        = c(1e6, 2, 1e6, 4, 1e6,
                            25, 6, 1e6, 6, 8,
                            1e6, 10, 1, 10, 12,
                            25, 14, 1e6, 14, 16,
                            1e6, 18, 1e6, 18, 20,
                            25, 22, 22, 1, 24,
                            1e6, 26, 26, 1e6, 28,
                            25, 1e6, 35, 1e6, 50),
      "mortageIncome"   = c(1e6, 30, 1e6, 30, 1e6,
                            100, 50, 1e6, 50, 60,
                            1e6, 70, 75, 70, 80,
                            100, 90, 1e6, 90, 100,
                            1e6, 110, 1e6, 110, 120,
                            100, 130, 130, 75, 140,
                            1e6, 150, 150, 1e6, 160,
                            100, 1e6, 175, 1e6, 200),
      "house_1_Cost"    = c(1e6, 10, 1e6, 20, 1e6, 
                            1e6, 30, 1e6, 30, 40, 
                            1e6, 50, 1e6, 50, 60,
                            1e6, 70, 1e6, 70, 80, 
                            1e6, 90, 1e6, 90, 100, 
                            1e6, 110, 110, 1e6, 120, 
                            1e6, 130, 130, 1e6, 150, 
                            1e6, 1e6, 175, 1e6, 200),
      "house_2_Cost"    = c(1e6, 30, 1e6, 60, 1e6, 
                            1e6, 90, 1e6, 90, 40, 
                            1e6, 100, 1e6, 150, 150,
                            1e6, 180, 1e6, 200, 200, 
                            1e6, 220, 1e6, 250, 250, 
                            1e6, 300, 330, 1e6, 360, 
                            1e6, 390, 390, 1e6, 450, 
                            1e6, 1e6, 500, 1e6, 600),
      "house_3_Cost"    = c(1e6, 90, 1e6, 180, 1e6, 
                            1e6, 270, 1e6, 270, 300, 
                            1e6, 450, 1e6, 450, 500,
                            1e6, 550, 1e6, 550, 600, 
                            1e6, 700, 1e6, 700, 750, 
                            1e6, 800, 800, 1e6, 850, 
                            1e6, 900, 900, 1e6, 1000, 
                            1e6, 1e6, 1100, 1e6, 1400),
      "house_4_Cost"    = c(1e6, 160, 1e6, 320, 1e6, 
                            1e6, 400, 1e6, 400, 450, 
                            1e6, 625, 1e6, 625, 700,
                            1e6, 750, 1e6, 750, 800, 
                            1e6, 875, 1e6, 875, 925, 
                            1e6, 975, 975, 1e6, 1025, 
                            1e6, 1100, 1100, 1e6, 1200, 
                            1e6, 1e6, 1300, 1e6, 1700),
      "house_hotel_Cost"    = c(1e6, 250, 1e6, 450, 1e6, 
                            1e6, 550, 1e6, 550, 600, 
                            1e6, 750, 1e6, 750, 900,
                            1e6, 950, 1e6, 950, 1000, 
                            1e6, 1050, 1e6, 1050, 1100, 
                            1e6, 1150, 1150, 1e6, 1200, 
                            1e6, 1275, 1275, 1e6, 1400, 
                            1e6, 1e6, 1500, 1e6, 2000),
      "XtileCoordinate" = c(1.46, 1.36, 1.28, 1.20, 1.12, 
                            1.04, 0.96, 0.88, 0.80, 0.72, 
                            0.56, 0.56, 0.56, 0.56, 0.56, 
                            0.56, 0.56, 0.56, 0.56, 0.56, 
                            0.64, 0.72, 0.80, 0.88, 0.96, 
                            1.04, 1.12, 1.20, 1.28, 1.36, 
                            1.53, 1.53, 1.53, 1.53, 1.53, 
                            1.53, 1.53, 1.53, 1.53, 1.53),
      "YtileCoordinate" = c(0.62, 0.62, 0.62, 0.62, 0.62, 
                            0.62, 0.62, 0.62, 0.62, 0.62, 
                            0.66, 0.76, 0.82, 0.92, 1.00, 
                            1.08, 1.16, 1.24, 1.32, 1.40, 
                            1.54, 1.54, 1.54, 1.54, 1.54, 
                            1.54, 1.54, 1.54, 1.54, 1.54, 
                            1.48, 1.40, 1.32, 1.24, 1.16, 
                            1.08, 1.00, 0.92, 0.84, 0.76)
    )
    #----------------------------------------------------------------------#
    
  
      ##------------------## Player Movement Function ##--------------------------##
movePlayer <- function(player_Data){
  
  roll <- dice(1) # 2
  updatePos <- player_Data$position + roll
  
  points(gameBoard$XtileCoordinate[player_Data$position], 
         gameBoard$YtileCoordinate[player_Data$position],
         type = "p",
         pch = 16,
         col = "white")
  points(gameBoard$XtileCoordinate[updatePos], 
         gameBoard$YtileCoordinate[updatePos],
         type = "p",
         pch = 16,
         col = player_Data$color) 
  
  player_Data$position <- updatePos
  
  if (player_Data$position > 40){
    
    points(gameBoard$XtileCoordinate[(player_Data$position - updatePos)], 
           gameBoard$YtileCoordinate[(player_Data$position - updatePos)],
           type = "p",
           pch = 16,
           col = "white")
    
    player_Data$position <- player_Data$position - 40
    
    points(gameBoard$XtileCoordinate[player_Data$position], 
           gameBoard$YtileCoordinate[player_Data$position],
           type = "p",
           pch = 16,
           col = player_Data$color) 
    
    #print("New GO!") # inactivatedyou 
    
    player_Data$money <- player_Data$money + 150 # 200
    moveList <- list(player_Data)
    
    return(moveList)
    
  } else {
    
    moveList <- list(player_Data)
    
    return(moveList)
  }
  
}
#----------------------------------------------------------------------------#

##------------------------## Chance Function ##-----------------------------##
chanceFunc <- function(player_Data){
  
  #jail <- 0
  
  dice_sum <- dice(3)
  
  chanceEvents_DF <- data.frame(
    c(3:18), 
    c("3#? Get out of jail-card.",
      "4#? Pay speeding ticket.",
      "5#? Street maintenance. 40 kr/house, 40 kr/hotel.",
      "6#? Property repair. 25 kr/house, 100kr/hotel.",
      "7#? Crossword price.",
      "8#? Go to Pennsylvania Stat. If pass GO, reap reward.",
      "9#? Go to JAIL!",
      "10#? Go to Illinois Av. If pass GO, take reward.",
      "11#? Payment on buildingloan.",
      "12#? Back three steps.",
      "13#? Go to GO!",
      "14#? Go to Boardwalk.",
      "15#? Go to St. Charles Place. If pass GO, reap reward.",
      "16#? Pay kindergarten fee.",
      "17#? Pay insider fine.",
      "18#? Gather savings interest.")
    )

  if (dice_sum == 3){
    
    next
    
  } else if (dice_sum == 4){
    
    player_Data$money <- player_Data$money - (15 * 5) # * 1
    
  } else if (dice_sum == 5){
    
    houses <- sum(
      c(sum(gameBoard$propPlayer == "1"), 
        sum(gameBoard$propPlayer == "2"),
        sum(gameBoard$propPlayer == "3"),
        sum(gameBoard$propPlayer == "4")
        )
      )
    
    hotels <- sum(
      sum(gameBoard$propPlayer == "H") 
      )
    
    streetBill <- houses * ( 40 * 3 ) + hotels * ( 40 * 3 ) # * 1
    
    # print("streetBill:") # inactivated
    # print(streetBill) # inactivated
    
    player_Data$money <- player_Data$money - streetBill
    
  } else if (dice_sum == 6){
    
    houses <- sum(
      c(sum(gameBoard$propPlayer == "1"), 
        sum(gameBoard$propPlayer == "2"),
        sum(gameBoard$propPlayer == "3"),
        sum(gameBoard$propPlayer == "4")
        )
      )
    
    hotels <- sum(
      sum(gameBoard$propPlayer == "H") 
      )
    
    repairBill <- houses*25 + hotels*100
    
    #print("repairBill:") # inactivated
    #print(repairBill) # inactivated
    
    player_Data$money <- player_Data$money - ( repairBill * 3 )  # * 1
    
  } else if (dice_sum == 7){
    
    player_Data$money <- player_Data$money + ( 100 * 2 )  # * 1
    
  } else if (dice_sum == 8){
    
    if (player_Data$position < 15){
      
      player_Data$position <- 15
      
    } else {
      
      player_Data$money <- player_Data$money + 150 # 200
      player_Data$position <- 15
      
    }
    
  } else if (dice_sum == 9){
    
    player_Data$position <- 11
    jail <- 1
    
  } else if (dice_sum == 10){
    
    if (player_Data$position < 25){
      
      player_Data$position <- 25
      
    } else {
      
      player_Data$money <- player_Data$money + 150 # 200
      player_Data$position <- 25
      
    }
    
  } else if (dice_sum == 11){
    
    player_Data$money <- player_Data$money + 150
    
  } else if (dice_sum == 12){
    
    player_Data$position <- player_Data$position - 3
    
  } else if (dice_sum == 13){
    
    player_Data$position <- 1
    
  } else if (dice_sum == 14){
    
    player_Data$position <- 40
    
  } else if (dice_sum == 15){
    if (player_Data$position < 12){
      
      player_Data$position <- 12
      
    } else {
      
      player_Data$money <- player_Data$money + 150 # 200
      player_Data$position <- 12
      
    }
  } else if (dice_sum == 16){
    
    player_Data$money <- player_Data$money - ( 150 * 3 )  # * 1
    
  } else if (dice_sum == 17){
    
    player_Data$money <- player_Data$money - ( 20 * 5 )  # * 1
    
  } else {
    
    player_Data$money <- player_Data$money + ( 50 * 3 )  # * 1
    
  }
  
  event <- chanceEvents_DF[dice_sum, 2]
  chanceEventList <- list(player_Data, dice_sum, event, jail)
  
  return(chanceEventList)
}
#----------------------------------------------------------------------------#


##--------------------## Community Chest Function ##------------------------##
communityChestFunc <- function(player_Data){
  
  #jail <- 0
  
  dice_sum <- dice(3)
  
  communityEvents_DF <- data.frame(
    c(3:18), 
    c("3#CC Get out of jail-card.",
      "4#CC Dentistpay.",
      "5#CC Pre-sold stock return.",
      "6#CC Mis-calc in your favour.",
      "7#CC Second-place in pageant.",
      "8#CC Divy on taxes.",
      "9#CC Go to JAIL!",
      "10#CC Pay insurance-premium.",
      "11#CC Annuity expires.",
      "12#CC Inheritance.",
      "13#CC Go to GO!",
      "14#CC Go to Mediterranean Av.",
      "15#CC Dividend on preference shares.",
      "16#CC Pay 10 kr in fines or chanse.",
      "17#CC Happy birthday! Take 10 kr / player.",
      "18#CC Private doctor fee.")
    )

  if (dice_sum == 3){
    
    next
    
  } else if (dice_sum == 4){
    
    player_Data$money <- player_Data$money - ( 100 * 3 )  # * 1
    
  } else if (dice_sum == 5){
    
    player_Data$money <- player_Data$money + ( 50 * 2 )  # * 1
    
  } else if (dice_sum == 6){
    
    player_Data$money <- player_Data$money + 150 # 200
    
  } else if (dice_sum == 7){
    
    player_Data$money <- player_Data$money + ( 10 * 3 )  # * 1
    
  } else if (dice_sum == 8){
    
    player_Data$money <- player_Data$money + ( 20 * 3 )  # * 1
    
  } else if (dice_sum == 9){
    
    player_Data$position <- 11
    jail <- 1
    
  } else if (dice_sum == 10){
    
    player_Data$money <- player_Data$money - ( 50 * 3 )  # * 1
    
  } else if (dice_sum == 11){
    
    player_Data$money <- player_Data$money + ( 100 * 2 )  # * 1
    
  } else if (dice_sum == 12){
    
    player_Data$money <- player_Data$money + ( 100 * 2 )  # * 1
    
  } else if (dice_sum == 13){
    
    player_Data$position <- 1
    
  } else if (dice_sum == 14){
    
    player_Data$position <- 2
    
  } else if (dice_sum == 15){
    
    player_Data$money <- player_Data$money + ( 25 * 3 )  # * 1
    
  } else if (dice_sum == 16){
    
    res <- rbinom(1, 1, 0.5)
    
    if (res == 0){
      
      player_Data$money <- player_Data$money - ( 10 * 5 )  # * 1
      
    } else {
      
      randomEventFunc(player_Data$position, player_Data)
      
    }
    
  } else if (dice_sum == 17){
    
    player_Data$money <- player_Data$money + ( 10 * 5 )  # * 1
    
  } else {
    
    player_Data$money <- player_Data$money - ( 50 * 3 )  # * 1
    
  }
  
  event <- communityEvents_DF[dice_sum, 2]
  CCEventList <- list(player_Data, dice_sum, event, jail)
  
  return(CCEventList)
}
#----------------------------------------------------------------------------#

    ##------------------------## Sell Tile Function ##--------------------------##
sellTileFunction <- function(player_Data, ownedColors, i, currentAction){

#print("sum, owned by:")
#print(sum(
#        (ownedColors$ownedBy == player_Data$name), 
#        na.rm = T))
#print("ownedColors:")
#print(ownedColors$ownedBy)
  
print("SellTileFunction [START]")
print("money_before:")
print(player_Data$money)

if (player_Data$money < 0 & 
      sum((gameBoard$ownedBy == player_Data$name),
          na.rm = T) < 1 &
     sum((gameBoard$ownedBy == player_Data$mortageStamp),
          na.rm = T) < 1) {
    print("SellTileFunction [START-1]")
    #-# Print how you will pay your debt #-#
    #print("You are broke! (1)")
    #print("You have no assets to sell. Game Over!")
    
    currentAction <- "Action: You are broke (1)!"
    #-#

    i <- 500
    
    #-# Game Over! #-#
    gameOver <- 1
    sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
    print("money_after:")
    print(player_Data$money)
    print("SellTileFunction [END-1]")
    return(sellOutputList)
    
  } else if (player_Data$money < 0 & 
      sum(
        (ownedColors$ownedBy == player_Data$name), 
        na.rm = T) < 1) {
    
    #-# Print how you will pay your debt #-#
    #print("You are broke! (2)")
    #print("You have assets to sell.")
    
    currentAction <- "Action: You are broke (2)!"
    #-#
  
    sellOrKeep <- which(gameBoard$ownedBy %in% player_Data$name)
    mortageThis <- which(gameBoard$tileCost[sellOrKeep] == min(gameBoard$tileCost[sellOrKeep]))

    gameBoard$ownedBy[sellOrKeep[mortageThis[1]]] <<- player_Data$mortageStamp
    
    ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[sellOrKeep[mortageThis[1]]])] <- NA
    
    #print("SellOrKeep:")
    #print(sellOrKeep)
    #print("SellOrKeep[mortageThis[1]]:")
    #print(sellOrKeep[mortageThis[1]])
    
    if(is.na(sellOrKeep[mortageThis[1]])){
      sellOrKeep <- which(gameBoard$ownedBy %in% player_Data$mortageStamp)
      mortageThis <- which(gameBoard$tileCost[sellOrKeep] == min(gameBoard$tileCost[sellOrKeep]))
  
      gameBoard$ownedBy[sellOrKeep[mortageThis[1]]] <<- "none"
      
      ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[sellOrKeep[mortageThis[1]]])] <- NA
      
      #print("SellOrKeep:")
      #print(sellOrKeep)
      #print("SellOrKeep[mortageThis[1]]:")
      #print(sellOrKeep[mortageThis[1]])
      
    } else {
      #-# Graphics #-#    
      a <- masterTileList[sellOrKeep[mortageThis[1]]]
      #print("a")
      #print(a)
      b_1 <- a[[1]][[1]]
      b_2 <- a[[1]][[2]]
      
      #print("b_1")
      #print(b_1)
      #print("b_2")
      #print(b_2)
      
      #cat("tileType:", gameBoard$tileType[sellThis])
      #print("mortageThis[1]:")
      #print(mortageThis[1])
      #print("gameBoard$tileType[mortageThis[1]]:")
      #print(gameBoard$tileType[mortageThis[1]])
      
      if (gameBoard$tileType[sellOrKeep[mortageThis[1]]] %in% c("T1", "T2", "T3", "T4","W", "E")) {
        polygon(b_1, b_2, col = "white", lty = "dotted", lwd = 2)
      } else {
        polygon(b_1, b_2, col = gameBoard$tileType[sellOrKeep[mortageThis[1]]], lty = "dotted", lwd = 2)
        # "pink"
      }
      
    } 
    
      print("SellTileFunction [START-2]")
  ## Player Sell Tile, Graphics [END]   ##
      #-# End of graphics #-#
  
      mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$tileCost[sellOrKeep[mortageThis[1]]]))
      
      propertyValue <- (
          ( as.numeric(unlist(gameBoard$tileRent[sellOrKeep[mortageThis[1]]])) 
          + 
          as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep[mortageThis[1]]]))
          )
          / 2)
  
      player_Data$money <- player_Data$money + propertyValue
      
      landValue <- mortageIncome_potentialTiles - propertyValue
        
      player_Data$money <- player_Data$money + ( landValue / 2 )
      player_Data$debtCounter <- landValue / 2
      #player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
  
      gameOver <- 0
      sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
      print("money_after:")
      print(player_Data$money)
      print("SellTileFunction [END-2]")
      return(sellOutputList) 
    
      
  } else if (player_Data$money < 0
             &
             sum(
        (ownedColors$ownedBy == player_Data$name), 
        na.rm = T) >= 1 
             ){
    
    #-# Print how you will pay your debt #-#
    #print("You are broke! (3)")
    #print("You have assets to sell, dont ruin your color monopoly!")
    
    #houseCost <- data.frame(
    #colors = c("brown", "cyan", "magenta", "orange", 
    #           "red", "yellow", "green", "blue"),
    #cost = c(50, 50, 100, 100, 150, 150, 200, 200)
    #)
    
    currentAction <- "Action: You are broke (3)!"
    #-#
    
    playerMonopolys <- ownedColors$ownedBy == player_Data$name

    ownedTiles <- gameBoard$tileType[gameBoard$ownedBy == player_Data$name]

    maybeMortage <- ownedTiles[((ownedTiles %in% ownedColors$colors[playerMonopolys]) == F)]

    maybeMortagePrice <- gameBoard$mortageIncome[gameBoard$tileType %in% maybeMortage]

    mortageTile <- which(gameBoard$tileNr == (which(gameBoard$mortageIncome == min(maybeMortagePrice))))
    #print("BEFORE IF length(maybeMortage):")
    #print(length(maybeMortage))
    
    if (length(maybeMortage) == 0){
      #print("#")
      #print("#")
      #print("#")
      print("SellTileFunction [START-3]")
      #print("### ### ### All your assets are monopolys. You have to sell some houses or tiles from an ubuilt monopoly! ### ### ### ")
      # Add code for when this happens - although it rarely happens. It might happen more often when I add counter players demanding rent.

    #ownedTiles <- gameBoard$tileType[gameBoard$ownedBy %in% player_Data$name]
    ownedTiles <- gameBoard$ownedBy %in% player_Data$name
    print("ownedTiles:")
    print(ownedTiles)
    maybeMortagePrice <- gameBoard$mortageIncome[ownedTiles]

    mortageTile <- which(gameBoard$tileNr == (which(gameBoard$mortageIncome == min(maybeMortagePrice))))
      
      n_houses <- gameBoard$propPlayer[mortageTile[1]] 
      #print("n_houses:")
      #print(n_houses)
      
      if (is.na(n_houses)) {
        n_houses <- "6"
      }
      
      n_houses <- sum(as.numeric(n_houses))
      #print("n_houses:")
      #print(n_houses)
      #print("is.na(n_houses):")
      #print(is.na(n_houses))
      
      #print("ownedBy: name")
      #print(gameBoard$ownedBy %in% player_Data$name)
      #print("ownedBy: stamp")
      #print(gameBoard$ownedBy %in% player_Data$mortageStamp)
      
      #print( ( sum(gameBoard$ownedBy %in% player_Data$name) + sum(gameBoard$ownedBy %in% player_Data$mortageStamp) ) )
      
      #print("mortageTile[1]:")
      #print(mortageTile[1])
      
      if ( ( sum(gameBoard$ownedBy %in% player_Data$name) + sum(gameBoard$ownedBy %in% player_Data$mortageStamp) ) == 0) {
        #print("if")
        gameOver <- 1
        i <- 500
        sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
        print("money_after:")
        print(player_Data$money)
        print("SellTileFunction [END-3]")
        return(sellOutputList)
      
      } else if (sum(n_houses, na.rm = T) > 0) {
        # selling all houses on a tile #
        #print("else if (1)")
        #print("houseCost$cost[gameBoard$tileType == gameBoard$tileType[mortageTile[1]]]:")
        #print( houseCost$cost[gameBoard$tileType == gameBoard$tileType[mortageTile[1]]] )
        
        mortageForNA <- gameBoard$ownedBy %in% player_Data$name
        mortageForNA <- min( gameBoard$mortageIncome[mortageForNA] )
        mortageForNA <-  ( gameBoard$mortageIncome %in% mortageForNA[1] )
        mortageForNA <- gameBoard$tileNr[mortageForNA]
        mortageForNA <- mortageForNA[1]
        #print("mortageForNA:")
        #print(mortageForNA)
        
        #print("test_a:")
        #print(gameBoard$tileType == gameBoard$tileType[mortageForNA])
        
        sellPrice <- houseCost$cost[gameBoard$tileType == gameBoard$tileType[mortageForNA]] # mortageTile[1]
        sellPrice <- sellPrice[1]
        sellPrice <- ( sellPrice / 2 ) * n_houses
        
        #print("sellPrice:")
        #print(sellPrice)
        
        if (is.na(sellPrice)){
          #print("if (2)")
          #print("else")
          sellOrKeep_2 <- which(gameBoard$ownedBy %in% player_Data$mortageStamp)
          mortageThis_2 <- which(gameBoard$tileCost[sellOrKeep_2] == min(gameBoard$tileCost[sellOrKeep_2]))
      
          gameBoard$ownedBy[sellOrKeep_2[mortageThis_2[1]]] <<- "none"
          
          ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[sellOrKeep_2[mortageThis_2[1]]])] <- NA
      
          #-# Graphics #-#    
          a <- masterTileList[[sellOrKeep_2[mortageThis_2[1]]]][1]
          b <- masterTileList[[sellOrKeep_2[mortageThis_2[1]]]][2]
          
          if (sellOrKeep_2[mortageThis_2[1]] <= 11) {
            polygon(
              c(a[[1]][1], 
                a[[1]][3], 
                a[[1]][2],
                a[[1]][4]),
            
              c(b[[1]][1],
                b[[1]][2],
                b[[1]][3], 
                b[[1]][4]),
            
                col = player_Data$color,
                border = "white",
                lwd = 2, 
                lty = "dashed"
                )
            
          } else if (sellOrKeep_2[mortageThis_2[1]] >= 12 
                 & 
                 sellOrKeep_2[mortageThis_2[1]]<= 21) {
            polygon(
              c(a[[1]][4], 
                a[[1]][1], 
                a[[1]][2],
                a[[1]][3]),
          
              c(b[[1]][2],
                b[[1]][4],
                b[[1]][3], 
                b[[1]][1]),
          
                col = player_Data$color,
                border = "white",
                lwd = 2, 
                lty = "dashed"
                )
        
          } else if (sellOrKeep_2[mortageThis_2[1]] >= 21 
                 & 
                 sellOrKeep_2[mortageThis_2[1]]<= 31) {
            polygon(
              c(a[[1]][1], 
                a[[1]][3], 
                a[[1]][2],
                a[[1]][4]),
          
              c(b[[1]][1],
                b[[1]][2],
                b[[1]][3], 
                b[[1]][4]),
          
                col = player_Data$color,
                border = "white",
                lwd = 2, 
                lty = "dashed"
                )
        
          } else {
            polygon(
              c(a[[1]][4], 
                a[[1]][1], 
                a[[1]][2],
                a[[1]][3]),
          
              c(b[[1]][2],
                b[[1]][4],
                b[[1]][3], 
                b[[1]][1]),
          
                col = player_Data$color,
                border = "white",
                lwd = 2, 
                lty = "dashed"
                )
          }
          #-# End of graphics #-#
          print("SellTileFunction [START-4]")
          #mortageIncome_potentialTiles_2 <- as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep_2[mortageThis_2[1]]]))
      
          #player_Data$money <- player_Data$money + mortageIncome_potentialTiles_2
          
          mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$tileCost[sellOrKeep_2[mortageThis_2[1]]]))
          
          #houseFrame <- gameBoard[]
          
          #print("houseFrame:")
          #print(houseFrame)
          print("number:")
          print(sellOrKeep_2[mortageThis_2[1]])
          print("HelaRaddan:")
          print(gameBoard[sellOrKeep_2[mortageThis_2[1]], (8 + as.numeric(n_houses))])
          
          propertyValue <- (
          ( as.numeric(unlist(gameBoard[sellOrKeep_2[mortageThis_2[1]], (8 + as.numeric(n_houses))])) 
          + 
          as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep_2[mortageThis_2[1]]]))
          )
          / 2)
  
          player_Data$money <- player_Data$money + propertyValue
          
          landValue <- mortageIncome_potentialTiles - propertyValue
            
          player_Data$money <- player_Data$money + ( landValue / 2 )
          player_Data$debtCounter <- landValue / 2
          #player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
      
          gameOver <- 0
          sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
          print("money_after:")
          print(player_Data$money)
          print("SellTileFunction [END-4]")
          return(sellOutputList)
        }
        
        #mortageIncome_potentialTiles_2 <- as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep_2[mortageThis_2[1]]]))
      
        #player_Data$money <- player_Data$money + mortageIncome_potentialTiles_2
        
        mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$tileCost[which(ownedColors$colors %in% gameBoard$tileType[mortageForNA])]))
        
        houseFrame <- gameBoard[8 + as.numeric(n_houses)]
        propertyValue <- (
        ( as.numeric(unlist(houseFrame[which(ownedColors$colors %in% gameBoard$tileType[mortageForNA])])) 
        + 
        as.numeric(unlist(gameBoard$mortageIncome[which(ownedColors$colors %in% gameBoard$tileType[mortageForNA])]))
        )
        / 2)

        player_Data$money <- player_Data$money + propertyValue
        
        landValue <- mortageIncome_potentialTiles - propertyValue
          
        player_Data$money <- player_Data$money + ( landValue / 2 )
        player_Data$debtCounter <- landValue / 2
        #player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
          
        #player_Data$money <- player_Data$money - sellPrice
        
        ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[mortageForNA])] <- NA
        
        gameBoard$propPlayer[mortageForNA] <- "0" # mortageForNA
        
        text(
        1.2, 
        0.85, 
        "Action: Sell buildings.", 
        col = player_Data$color, 
        cex = 0.95, 
        )
        currentAction <- "Action: Sell buildings."
        
        #-# Graphics #-#
        a <- masterTileList[[mortageForNA]][1] # mortageTile[1]
        b <- masterTileList[[mortageForNA]][2] # mortageTile[1]
        
        if (gameBoard$tileNr[mortageForNA] <= 11) { # mortageTile[1]
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
          
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
          
              col = player_Data$color,
              border = "black"
            )
          
        } else if (gameBoard$tileNr[mortageForNA] >= 12  # mortageTile[1]
               & 
               gameBoard$tileNr[mortageForNA]<= 21) { # mortageTile[1]
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
            col = player_Data$color,
            border = "black"
            )
      
        } else if (gameBoard$tileNr[mortageForNA] >= 21 # mortageTile[1]
               & 
               gameBoard$tileNr[mortageForNA]<= 31) { # mortageTile[1]
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
        
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
        
            col = player_Data$color,
            border = "black"
            )
      
        } else {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
            col = player_Data$color,
            border = "black"
          )
          }
        #-# End of Graphics #-#
        
      } else {
        #print("else")
        sellOrKeep <- which(gameBoard$ownedBy %in% player_Data$name)
        mortageThis <- which(gameBoard$tileCost[sellOrKeep] == min(gameBoard$tileCost[sellOrKeep]))
    
        gameBoard$ownedBy[sellOrKeep[mortageThis[1]]] <<- player_Data$mortageStamp
        
        ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[sellOrKeep[mortageThis[1]]])] <- NA
    
        #-# Graphics #-#    
        a <- masterTileList[[sellOrKeep[mortageThis[1]]]][1]
        b <- masterTileList[[sellOrKeep[mortageThis[1]]]][2]
        
        if (sellOrKeep[mortageThis[1]] <= 11) {
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
          
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
          
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
          
        } else if (sellOrKeep[mortageThis[1]] >= 12 
               & 
               sellOrKeep[mortageThis[1]]<= 21) {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
      
        } else if (sellOrKeep[mortageThis[1]] >= 21 
               & 
               sellOrKeep[mortageThis[1]]<= 31) {
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
        
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
        
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
      
        } else {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
        }
        #-# End of graphics #-#
        print("SellTileFunction [START-5]")
        #mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep[mortageThis[1]]]))
        
        #mortageIncome_potentialTiles_2 <- as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep_2[mortageThis_2[1]]]))
        print("A")
        mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$tileCost[sellOrKeep[mortageThis[1]]]))
        print("B")

        propertyValue <- (
        ( as.numeric(unlist(gameBoard[sellOrKeep[mortageThis[1]], (8 + as.numeric(n_houses))])) 
        + 
        as.numeric(unlist(gameBoard$mortageIncome[sellOrKeep[mortageThis[1]]]))
        )
        / 2)
        print("propertyValue:")
        print(propertyValue)
        print("C")
        player_Data$money <- player_Data$money + propertyValue
        
        landValue <- mortageIncome_potentialTiles - propertyValue
          
        player_Data$money <- player_Data$money + ( landValue / 2 )
        player_Data$debtCounter <- landValue / 2
        #player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
        
        #player_Data$money <- player_Data$money + mortageIncome_potentialTiles
    
        gameOver <- 0
        sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
        print("Covert Output")
        return(sellOutputList)
      }

      gameOver <- 0
      sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
      print("money_after:")
      print(player_Data$money)
      print("SellTileFunction [END-5]")
      return(sellOutputList)
      
    } else {
      
      #cat("ELSE length(maybeMortage):", length(maybeMortage))
      #print("MORTAGETILE 1")
      #print(mortageTile[1])
      #print("gameBoard$ownedBy[player_Data$name]")
      #print(gameBoard$ownedBy[player_Data$name])
      #print("gameBoard$ownedBy[player_Data$mortageStamp]")
      #print(gameBoard$ownedBy[player_Data$mortageStamp])
      
      #print(sum(gameBoard$ownedBy == player_Data$name) + sum(gameBoard$ownedBy == player_Data$mortageStamp))
      
      #print("sum(mortageTile, na.rm = T):")
      #print(sum(mortageTile, na.rm = T))
      
      if ( sum(mortageTile, na.rm = T) == 0 ) {
        mortageSale <- gameBoard$ownedBy %in% player_Data$mortageStamp
        print(mortageSale)
        min_mortageSale <- min( gameBoard$tileCost[mortageSale] )
        
        print("min_mortageSale:")
        print(min_mortageSale)
        
        gameBoard$ownedBy[min_mortageSale[1]] <<- player_Data$mortageStamp
      
        ownedColors$ownedBy[which(ownedColors$colors %in%(gameBoard$tileType[min_mortageSale[1]]))] <- NA
        
        #-# Graphics #-#
        a <- masterTileList[[min_mortageSale[1]]][1]
        b <- masterTileList[[min_mortageSale[1]]][2]
      
        if (min_mortageSale[1] <= 11) {
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
          
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
          
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
          
        } else if (min_mortageSale[1] >= 12 
               & 
               min_mortageSale[1] <= 21) {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
      
        } else if (min_mortageSale[1] >= 21 
               & 
               min_mortageSale[1] <= 31) {
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
        
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
        
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
      
        } else {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
              col = player_Data$color,
              border = "white",
              lwd = 2, 
              lty = "dashed"
              )
        }
        print("SellTileFunction [START-6]")
        #-# End of graphics #-#
        print("min_mortageSale[1]:")
        print(min_mortageSale[1])
        
        mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$mortageIncome[min_mortageSale[1]]))
        
        propertyValue <- 
          as.numeric(unlist(gameBoard$tileRent[min_mortageSale[1]]))

        player_Data$money <- player_Data$money + propertyValue
        
        landValue <- mortageIncome_potentialTiles - propertyValue
          
        player_Data$money <- player_Data$money + ( landValue / 2 )
        player_Data$debtCounter <- landValue / 2
        
        #player_Data$money <- player_Data$money + gameBoard$tileCost[min_mortageSale[1]]
        
        gameOver <- 0
        sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
        print("money_after:")
        print(player_Data$money)
        print("SellTileFunction [END-6]")
        return(sellOutputList)
        
        
      }
      
      if ( ( sum(gameBoard$ownedBy %in% player_Data$name) + sum(gameBoard$ownedBy %in% player_Data$mortageStamp) ) == 0) {
        
        print("SellTileFunction [START-7]")
        gameOver <- 1
        i <- 500
        sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
        print("money_after:")
        print(player_Data$money)
        print("SellTileFunction [END-7]")
        return(sellOutputList)
      
      }
      
      gameBoard$ownedBy[mortageTile[1]] <<- player_Data$mortageStamp
      
      ownedColors$ownedBy[which(ownedColors$colors %in%(gameBoard$tileType[mortageTile[1]]))] <- NA
      
      #-# Graphics #-#
      a <- masterTileList[[mortageTile[1]]][1]
      b <- masterTileList[[mortageTile[1]]][2]
    
      if (mortageTile[1] <= 11) {
        polygon(
          c(a[[1]][1], 
            a[[1]][3], 
            a[[1]][2],
            a[[1]][4]),
        
          c(b[[1]][1],
            b[[1]][2],
            b[[1]][3], 
            b[[1]][4]),
        
            col = player_Data$color,
            border = "white",
            lwd = 2, 
            lty = "dashed"
            )
        
      } else if (mortageTile[1] >= 12 
             & 
             mortageTile[1] <= 21) {
        polygon(
          c(a[[1]][4], 
            a[[1]][1], 
            a[[1]][2],
            a[[1]][3]),
      
          c(b[[1]][2],
            b[[1]][4],
            b[[1]][3], 
            b[[1]][1]),
      
            col = player_Data$color,
            border = "white",
            lwd = 2, 
            lty = "dashed"
            )
    
      } else if (mortageTile[1] >= 21 
             & 
             mortageTile[1] <= 31) {
        polygon(
          c(a[[1]][1], 
            a[[1]][3], 
            a[[1]][2],
            a[[1]][4]),
      
          c(b[[1]][1],
            b[[1]][2],
            b[[1]][3], 
            b[[1]][4]),
      
            col = player_Data$color,
            border = "white",
            lwd = 2, 
            lty = "dashed"
            )
    
      } else {
        polygon(
          c(a[[1]][4], 
            a[[1]][1], 
            a[[1]][2],
            a[[1]][3]),
      
          c(b[[1]][2],
            b[[1]][4],
            b[[1]][3], 
            b[[1]][1]),
      
            col = player_Data$color,
            border = "white",
            lwd = 2, 
            lty = "dashed"
            )
      }
      #-# End of graphics #-#
      print("SellTileFunction [START-8]")
      mortageIncome_potentialTiles <- as.numeric(unlist(gameBoard$mortageIncome[mortageTile[1]]))
        
      propertyValue <- 
        as.numeric(unlist(gameBoard$tileRent[mortageTile[1]]))

      player_Data$money <- player_Data$money + propertyValue
      
      #landValue <- mortageIncome_potentialTiles - propertyValue
      landValue <- mortageIncome_potentialTiles - propertyValue
        
      player_Data$money <- player_Data$money + ( landValue / 2 )
      player_Data$debtCounter <- landValue / 2
        
      #player_Data$money <- player_Data$money + gameBoard$mortageIncome[mortageTile[1]]
  
      gameOver <- 0
      sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
      print("money_after:")
      print(player_Data$money)
      print("SellTileFunction [END-8]")
      return(sellOutputList)
    }
    
  } else {
    #print("Continue...") # inactivated
  }
  print("SellTileFunction [START-9]")
  gameOver <- 0
  sellOutputList <- list(player_Data, ownedColors, i, gameOver, currentAction)
  print("money_after:")
  print(player_Data$money)
  print("SellTileFunction [END-9]")
  return(sellOutputList)
}
#----------------------------------------------------------------------------#  
      
    ##------------------------## Buy Tile Function ##---------------------------##
buyTileFunction <- function(player_Data, ownedColors, currentAction){

if (gameBoard$ownedBy[player_Data$position] == "none" 
    &
    player_Data$money >= gameBoard$tileCost[player_Data$position]){
      
      # print("Action: buy.") # inactivated since appears too freq.
      text(
        1.2, 
        0.85, 
        "Action: buy.", 
        col = player_Data$color, 
        cex = 0.95, 
      )
      currentAction <- "Action: buy tile."
      
      #-# Graphics #-#
      a <- masterTileList[[player_Data$position]][1]
      b <- masterTileList[[player_Data$position]][2]
      
      if (gameBoard$tileNr[player_Data$position] <= 11) {
        polygon(
          c(a[[1]][1], 
            a[[1]][3], 
            a[[1]][2],
            a[[1]][4]),
        
          c(b[[1]][1],
            b[[1]][2],
            b[[1]][3], 
            b[[1]][4]),
        
            col = player_Data$color,
            border = "black"
          )
        
      } else if (gameBoard$tileNr[player_Data$position] >= 12 
             &  
             gameBoard$tileNr[player_Data$position]<= 21) {
        polygon(
          c(a[[1]][4], 
            a[[1]][1], 
            a[[1]][2],
            a[[1]][3]),
      
          c(b[[1]][2],
            b[[1]][4],
            b[[1]][3], 
            b[[1]][1]),
      
          col = player_Data$color,
          border = "black"
          )
    
      } else if (gameBoard$tileNr[player_Data$position] >= 21 
             & 
             gameBoard$tileNr[player_Data$position]<= 31) {
        polygon(
          c(a[[1]][1], 
            a[[1]][3], 
            a[[1]][2],
            a[[1]][4]),
      
          c(b[[1]][1],
            b[[1]][2],
            b[[1]][3], 
            b[[1]][4]),
      
          col = player_Data$color,
          border = "black"
          )
    
      } else {
        polygon(
          c(a[[1]][4], 
            a[[1]][1], 
            a[[1]][2],
            a[[1]][3]),
      
          c(b[[1]][2],
            b[[1]][4],
            b[[1]][3], 
            b[[1]][1]),
      
          col = player_Data$color,
          border = "black"
        )
        }
      #-# End of Graphics #-#
      
      #-# New values #-#
      player_Data$money <- player_Data$money -
      gameBoard$tileCost[player_Data$position]
  
      gameBoard$ownedBy[player_Data$position] <<- player_Data$name
      #-#

      } else if (
        sum(gameBoard$tileType[gameBoard$ownedBy == player_Data$name] 
        == gameBoard$tileType[player_Data$position]) == 3 
        || 
        sum(gameBoard$tileType[gameBoard$ownedBy == player_Data$name] 
        == gameBoard$tileType[player_Data$position]) == 2 && 
        "brown" %in% gameBoard$tileType[player_Data$position] 
        || 
        sum(gameBoard$tileType[gameBoard$ownedBy == player_Data$name] 
        == gameBoard$tileType[player_Data$position]) == 2 && 
        "blue" %in% gameBoard$tileType[player_Data$position]
        ){
        
        #-# New values #-#
        ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[player_Data$position])] <<- player_Data$name
        
        player_Data$money <- drawHousesFunc(player_Data)
        #-#
        
      } else {
        #print("Action: too expensive.") # inactivated since appears too freq.
        text(
          1.2, 
          0.85, 
          "Action: too expensive.", 
          col = player_Data$color, 
          cex = 0.95, 
        )
        #currentAction <- "Action: Too expensive." # inactivated since appears too freq.
      }

    buyOutputList <- list(player_Data, ownedColors, currentAction)
    
  return(buyOutputList)
}
#----------------------------------------------------------------------------#


##-----------------------## Mortage Flip Functions ##-----------------------##
mortageFlipFunction <- function(player_Data, ownedColors, currentAction){
  print("MortageFlip [START]")
  print("money_before:")
  print(player_Data$money)
  #-# Finding which tiles can be mortaged #-#
  posibleMortage <- gameBoard$mortageIncome[gameBoard$ownedBy 
                                       == player_Data$mortageStamp]
  
  affordableMortage <- player_Data$money >= posibleMortage
  
  player_Data$money <- player_Data$money - ( posibleMortage[max(affordableMortage)] * 1.1 ) # added * 1.1
  
  positionProxy_all <- gameBoard$tileNr[gameBoard$mortageIncome == posibleMortage[max(affordableMortage)]]
  positionProxy <- positionProxy_all[1]
  #-#
  
  #-# New values #-#
  gameBoard$ownedBy[positionProxy] <<- player_Data$name
  
  currentAction <- "Action: Mortage flipped."
  #-#
  
  #-# Graphics #-#
  if (positionProxy >= 0){
    
        # print("Action: buy.") # inactivated since appears too freq.
        
        a <- masterTileList[[positionProxy]][1]
        b <- masterTileList[[positionProxy]][2]
        
        if (gameBoard$tileNr[positionProxy] <= 11) {
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
          
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
          
              col = player_Data$color,
              border = "black"
            )
          
        } else if (gameBoard$tileNr[positionProxy] >= 12 
               & 
               gameBoard$tileNr[positionProxy]<= 21) {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
            col = player_Data$color,
            border = "black"
            )
      
        } else if (gameBoard$tileNr[positionProxy] >= 22 
               & 
               gameBoard$tileNr[positionProxy]<= 31) {
          polygon(
            c(a[[1]][1], 
              a[[1]][3], 
              a[[1]][2],
              a[[1]][4]),
        
            c(b[[1]][1],
              b[[1]][2],
              b[[1]][3], 
              b[[1]][4]),
        
            col = player_Data$color,
            border = "black"
            )
      
        } else {
          polygon(
            c(a[[1]][4], 
              a[[1]][1], 
              a[[1]][2],
              a[[1]][3]),
        
            c(b[[1]][2],
              b[[1]][4],
              b[[1]][3], 
              b[[1]][1]),
        
            col = player_Data$color,
            border = "black"
          )
        }
  }
  #-# End of graphics #-#
  
  if (
          sum(gameBoard$tileType[gameBoard$ownedBy == player_Data$name] 
          == gameBoard$tileType[positionProxy]) == 3 
          || 
          sum(gameBoard$tileType[gameBoard$ownedBy == player_Data$name] 
          == gameBoard$tileType[positionProxy]) == 2 && 
          "brown" %in% gameBoard$tileType[positionProxy] 
          || 
          sum(gameBoard$tileType[gameBoard$ownedBy == player_Data$name] 
          == gameBoard$tileType[positionProxy]) == 2 && 
          "blue" %in% gameBoard$tileType[positionProxy]
          ){
          
           #-# Graphics #-#
           a <- masterTileList[[positionProxy]][1] ### Added the graphics in because mortage fliped tiles on brown were not being drawn
           b <- masterTileList[[positionProxy]][2]
          
           if (gameBoard$tileNr[positionProxy] <= 11) {
             polygon(
              c(a[[1]][1], 
                a[[1]][3], 
                a[[1]][2],
                a[[1]][4]),
            
              c(b[[1]][1],
                b[[1]][2],
                b[[1]][3], 
                b[[1]][4]),
            
                col = player_Data$color,
                border = "black" #black
              )
            
           } else if (gameBoard$tileNr[positionProxy] >= 12 
                 & 
                 gameBoard$tileNr[positionProxy]<= 21) {
             polygon(
              c(a[[1]][4], 
                a[[1]][1], 
                a[[1]][2],
                a[[1]][3]),
          
              c(b[[1]][2],
                b[[1]][4],
                b[[1]][3], 
                b[[1]][1]),
          
              col = player_Data$color,
              border = "black" #black
              )
        
           } else if (gameBoard$tileNr[positionProxy] >= 22 
                 & 
                 gameBoard$tileNr[positionProxy]<= 31) {
            polygon(
              c(a[[1]][1], 
                a[[1]][3], 
                a[[1]][2],
                a[[1]][4]),
          
              c(b[[1]][1],
                b[[1]][2],
                b[[1]][3], 
                b[[1]][4]),
          
              col = player_Data$color,
              border = "black" #black
              )
        
           } else {
             polygon(
              c(a[[1]][4], 
                a[[1]][1], 
                a[[1]][2],
                a[[1]][3]),
          
              c(b[[1]][2],
                b[[1]][4],
                b[[1]][3], 
                b[[1]][1]),
          
              col = player_Data$color,
              border = "black" #black
            )
           }
           #-# End of graphics #-#
          
          #-# New values #-#
          ownedColors$ownedBy[which(ownedColors$colors %in% gameBoard$tileType[positionProxy])] <<- player_Data$name
          #-#
          
  } 
  
  mortageFlipOut <- list(player_Data, ownedColors, currentAction)
  print("money_after:")
  print(player_Data$money)
  print("MortageFlip [END]")
  return(mortageFlipOut)
}
#----------------------------------------------------------------------------# 
drawHousesFunc <- function(player_Data){
  
  #-# value to be returned() #-#
  houseMoney <- player_Data$money
  #-#
  
  #-# Graphics and Logic #-#
  if (gameBoard$tileNr[player_Data$position] <= 11) {
          
          if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("0","1")) == T) == T 
              & 
              player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
              &
              gameBoard$propPlayer[player_Data$position] == "0"
              ) {
            
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "1", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "1"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
    
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("1","2")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "1"
                     )
                     {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "1", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "2", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "2"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("2","3")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "2"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "2", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "3", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "3"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("3","4")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "3"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "3", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "4", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "4"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
            
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("4","H")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "4"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "4", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] + 0.035, 
              "H", 
              col = "red", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "H"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          }
    
          
        } else if (gameBoard$tileNr[player_Data$position] >= 12 
             & 
             gameBoard$tileNr[player_Data$position]<= 21) {
          
          if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("0","1")) == T) == T   
              & 
              player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
              &
              gameBoard$propPlayer[player_Data$position] == "0"
              ) {
            
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "1", 
              col = "green", 
              cex = 0.95, 
              srt = 90
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "1"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("1","2")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "1"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "1", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 90
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "2", 
              col = "green", 
              cex = 0.95, 
              srt = 90
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "2"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("2","3")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "2"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "2", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 90
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "3", 
              col = "green", 
              cex = 0.95, 
              srt = 90
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "3"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("3","4")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "3"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "3", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 90
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "4", 
              col = "green", 
              cex = 0.95, 
              srt = 90
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "4"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("4","H")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "4"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "4", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 90
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] + 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "H", 
              col = "red", 
              cex = 0.95, 
              srt = 90
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "H"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          }
          
        } else if (gameBoard$tileNr[player_Data$position] >= 21 
             & 
             gameBoard$tileNr[player_Data$position]<= 31) {
          
          if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("0","1")) == T) == T 
              & 
              player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
              &
              gameBoard$propPlayer[player_Data$position] == "0"
              ) {
            
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "1", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "1"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("1","2")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "1"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "1", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "2", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "2"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("2","3")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "2"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "2", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "3", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "3"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("3","4")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "3"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "3", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "4", 
              col = "green", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "4"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("4","H")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "4"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "4", 
              col = player_Data$color, 
              cex = 0.95, 
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position], 
              gameBoard$YtileCoordinate[player_Data$position] - 0.035, 
              "H", 
              col = "red", 
              cex = 0.95, 
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "H"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          }
          
        } else {
          
          if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("0","1")) == T) == T  
              & 
              player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
              &
              gameBoard$propPlayer[player_Data$position] == "0"
              ) {
            
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "1", 
              col = "green", 
              cex = 0.95, 
              srt = 270
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "1"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("1","2")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "1"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "1", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 270
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "2", 
              col = "green", 
              cex = 0.95, 
              srt = 270
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "2"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("2","3")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "2"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "2", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 270
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "3", 
              col = "green", 
              cex = 0.95, 
              srt = 270
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "3"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("3","4")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "3"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "3", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 270
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "4", 
              col = "green", 
              cex = 0.95, 
              srt = 270
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "4"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          } else if (all((gameBoard$propPlayer[which(gameBoard$tileType == gameBoard$tileType[player_Data$position])] %in% c("4","H")) == T) == T 
                     & 
                     player_Data$money >= houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
                     &
                     gameBoard$propPlayer[player_Data$position] == "4"
                     ) {
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "4", 
              col = player_Data$color, 
              cex = 0.95, 
              srt = 270
              )
            text(
              gameBoard$XtileCoordinate[player_Data$position] - 0.035, 
              gameBoard$YtileCoordinate[player_Data$position], 
              "H", 
              col = "red", 
              cex = 0.95, 
              srt = 270
              )
            
            gameBoard$propPlayer[player_Data$position] <<- "H"
            
            houseMoney <- player_Data$money -
      houseCost$cost[which(houseCost$colors == gameBoard$tileType[player_Data$position])]
            
            return(houseMoney)
          
          }
          
        }
  
  return(houseMoney)
}
      
    ##----------------## Current player Game Loop Function ##-------------------##
gameLoop <- function(framePause, 
                     n_loops, 
                     player_Data,
                     roundNr,
                     monopoly,
                     cur_Action,
                     jail) { # jail = 0
  
  currentAction <- "UNDEFINED"
  #cat("GameLoop, jail, test:", jail)
  
  for (i in 1:n_loops) {
    
    # inactivated since appears too freq.
    
    #print(
    #c("Players turn" = player_Data$name,
    #  "tileNr:" = gameBoard$tileNr[player_Data$position], 
    #  "tileType:" = gameBoard$tileType[player_Data$position], 
    #  "ownedBy:" = gameBoard$ownedBy[player_Data$position],
    #  "player money:" = player_Data$money)
    #) 
    
    ## Game Stats, Graphics [START] ##
    text(
      0.74, 
      0.8, 
      "'roundNr':", 
      col = "black", 
      cex = 0.95, 
    )
    text(
      0.84, 
      0.8, 
      roundNr, 
      col = "blue", 
      cex = 0.95, 
    )
    ## Game Stats, Graphics [END] ##
    
    ## Player Stats, Graphics [START] ## 
    text(
      1.05, 
      0.8, 
      "'tileNr':", 
      col = player_Data$color, 
      cex = 0.95, 
    )
    text(
      1.11, 
      0.8, 
      gameBoard$tileNr[player_Data$position], 
      col = "blue", 
      cex = 0.95, 
    )
    
    text(
      1.2, 
      0.8, 
      "'tileType':", 
      col = player_Data$color, 
      cex = 0.95, 
    )
    text(
      1.32, 
      0.8, 
      gameBoard$tileType[player_Data$position], 
      col = "blue", 
      cex = 0.95, 
    )
    
    text(
      1.08, 
      0.76, 
      "'ownedBy':", 
      col = player_Data$color, 
      cex = 0.95, 
    )
    text(
      1.2, 
      0.76, 
      gameBoard$ownedBy[player_Data$position], 
      col = "blue", 
      cex = 0.95, 
    )
    
    text(
      1.3, 
      0.76, 
      round(player_Data$money), 
      col = "darkgreen", 
      cex = 0.95, 
    )
    text(
      1.38, 
      0.76, 
      "$", 
      col = "darkgreen", 
      cex = 0.95, 
    )
    
    if (gameBoard$tileType[player_Data$position] == "I") {
      player_Data$money <- player_Data$money - ( 200 * 3 ) # * 1
      #print("Action: pay income tax.") # inactivated
      currentAction <- "Action: pay income tax."
      text(
        1.2, 
        0.90,
        "Action: pay income tax.", 
        col = player_Data$color, 
        cex = 0.95, 
      )
    } else if (gameBoard$tileType[player_Data$position] == "S") {
      player_Data$money <- player_Data$money - ( 100 * 3 ) # 1
      #print("Action: pay super tax.") # inactivated
      currentAction <- "Action: pay super tax."
      text(
        1.2, 
        0.90,
        "Action: pay super tax.", 
        col = player_Data$color, 
        cex = 0.95, 
      )
    } else if (gameBoard$tileType[player_Data$position] == "CC"){
      
      randCC <- communityChestFunc(player_Data)
      
      # update player #
      points(gameBoard$XtileCoordinate[player_Data$position], 
             gameBoard$YtileCoordinate[player_Data$position],
             type = "p",
             pch = 16,
             col = "white")

      player_Data <- randCC[[1]]
      dice_sum <- randCC[[2]]
      event <- randCC[[3]]
      jail <- randCC[[4]]
      #print(event) # inactivated
      currentAction <- event
      text(
        1.2, 
        0.90,
        paste0("CC#:", dice_sum), 
        col = player_Data$color, 
        cex = 0.95, 
      )
      
    } else if (gameBoard$tileType[player_Data$position] == "?"){
      
      randChance <- chanceFunc(player_Data)
      
      # update player #
      points(gameBoard$XtileCoordinate[player_Data$position], 
             gameBoard$YtileCoordinate[player_Data$position],
             type = "p",
             pch = 16,
             col = "white")

      player_Data <- randChance[[1]]
      dice_sum <- randChance[[2]]
      event <- randChance[[3]]
      jail <- randChance[[4]]
      
      #print(event) # inactivated
      currentAction <- event
      text(
        1.2, 
        0.90,
        paste0("?#:", dice_sum), 
        col = player_Data$color, 
        cex = 0.95, 
      )
      
    } else if (gameBoard$tileType[player_Data$position] == "GT_J") {
      #print("Action: go to jail!") # inactivated
      currentAction <- "Action: go to jail!"
      text(
        1.2, 
        0.90,
        "Action: go to jail!", 
        col = player_Data$color, 
        cex = 0.95, 
      )
      
      points(gameBoard$XtileCoordinate[player_Data$position], 
             gameBoard$YtileCoordinate[player_Data$position],
             type = "p",
             pch = 16,
             col = "white")
      player_Data$position <- 11
      jail <- 1
      points(gameBoard$XtileCoordinate[player_Data$position], 
             gameBoard$YtileCoordinate[player_Data$position],
             type = "p",
             pch = 16,
             col = player_Data$color)
    ## Player Stats, Graphics [END] ##
      
    } else if ( gameBoard$ownedBy[player_Data$position] 
                %in% 
                c("!", "none", player_Data$name, player_Data$mortageStamp) == F){
     # update player #
      points(gameBoard$XtileCoordinate[player_Data$position], 
             gameBoard$YtileCoordinate[player_Data$position],
             type = "p",
             pch = 16,
             col = "white")
      text(
        1.2, 
        0.90,
        "Action: pay rent!", 
        col = player_Data$color, 
        cex = 0.95, 
      )
      currentAction <- "Action: pay rent!"
      #print("Pay rent!")
      ################
      #print("player_Data:")
      #print(player_Data)
      player_Data <<- player_Data
      
      if (gameBoard$propPlayer[player_Data$position] 
          == "0"){
        #print("#")
        #print("0")
        #print("#")
        #cat("propPlayer:", player_Data$position)
        #print("player_Data:")
        #print(player_Data)
        if ( gameBoard$propPlayer[player_Data$position] == "0" &
            (gameBoard$tileType[player_Data$position] %in% 
            ownedColors$colors[c(player_Data$name, "none")] == F)
            ){
          
          #print("A MONOPOLY!")
          #print("Money before rent:")
          #print(player_Data$money)
          player_Data$money <- player_Data$money - ( (2 * gameBoard$tileRent[player_Data$position]) * 4) # 2 *
          player_Data$debtCounter <- 2 * (4 * gameBoard$tileRent[player_Data$position]) # 2 *
          player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
          #print("Money after rent:")
          #print(player_Data$money)
        } else {
          
          player_Data$money <- player_Data$money - ( gameBoard$tileRent[player_Data$position] * 4 ) # 2 *
          player_Data$debtCounter <- gameBoard$tileRent[player_Data$position] * 4 # 2 *
          player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
          
        }
      
      } else if (gameBoard$propPlayer[player_Data$position] 
                 == "1"){
        #print("#")
        #print("1")
        #print("#")
        #print("player_Data:")
        #print(player_Data)
        #cat("propPlayer:", player_Data$position)
        #print("house_1 cost:")
        #print(gameBoard$house_1_Cost[player_Data$position])
        #print("Money before rent:")
        #print(player_Data$money)
          
        player_Data$money <- player_Data$money - ( gameBoard$house_1_Cost[player_Data$position] * 4 ) # 2 *
        player_Data$debtCounter <- gameBoard$house_1_Cost[player_Data$position] * 4 # 2 *
        player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
        
        #print("Money after rent:")
        #print(player_Data$money)
      
      } else if (gameBoard$propPlayer[player_Data$position] 
                 == "2"){
        #print("#")
        #print("2")
        #print("#")
        #print("player_Data:")
        #print(player_Data)
        #cat("propPlayer:", player_Data$position)
        
        #print("Money before rent:")
        #print(player_Data$money)
          
        player_Data$money <- player_Data$money - ( gameBoard$house_2_Cost[player_Data$position] * 4 ) # 2 *
        player_Data$debtCounter <- gameBoard$house_2_Cost[player_Data$position] * 4 # 2 *
        player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
        
        #print("Money after rent:")
        #print(player_Data$money)
      
      } else if (gameBoard$propPlayer[player_Data$position] 
                 == "3"){
        #print("#")
        #print("3")
        #print("#")
        #print("player_Data:")
        #print(player_Data)
        #cat("propPlayer:", player_Data$position)
        
        #print("Money before rent:")
        #print(player_Data$money)
          
        player_Data$money <- player_Data$money - ( gameBoard$house_3_Cost[player_Data$position] * 4 ) # 2 *
        player_Data$debtCounter <- gameBoard$house_3_Cost[player_Data$position] * 4 # 2 *
        player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
        
        #print("Money after rent:")
        #print(player_Data$money)
      
      } else if (gameBoard$propPlayer[player_Data$position] 
                 == "4"){
        #print("#")
        #print("4")
        #print("#")
        #print("player_Data:")
        #print(player_Data)
        #cat("propPlayer:", player_Data$position)
        
        #print("Money before rent:")
        #print(player_Data$money)
          
        player_Data$money <- player_Data$money - ( gameBoard$house_4_Cost[player_Data$position] * 4 ) # 2 *
        player_Data$debtCounter <- gameBoard$house_4_Cost[player_Data$position] * 4 # 2 *
        player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
        
        #print("Money after rent:")
        #print(player_Data$money)
      
      } else if (gameBoard$propPlayer[player_Data$position] 
                 == "H"){
        #print("#")
        #print("H")
        #print("#")
        #print("player_Data:")
        #print(player_Data)
        #cat("propPlayer:", player_Data$position)
        
        #print("Money before rent:")
        #print(player_Data$money)
          
        player_Data$money <- player_Data$money - ( gameBoard$house_hotel_Cost[player_Data$position] * 4 ) # 2 *
        player_Data$debtCounter <- gameBoard$house_hotel_Cost[player_Data$position] * 4 # 2 *
        player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
        
        #print("Money after rent:")
        #print(player_Data$money)
      
      } else if ( gameBoard$propPlayer[player_Data$position] 
                 %in% "T" ) 
      { 
          #print("!")
          #cat("propPlayer:", player_Data$position)
        
          #print("YOU LANDED ON A TRAIN STATION!")
          #print(gameBoard$tileType[player_Data$position])
          
          oponentTiles <- gameBoard$ownedBy[c(6, 16, 26, 36)] %in% 
                  c("!", "none", player_Data$name, player_Data$mortageStamp)
          #cat("oponentTiles:", oponentTiles)
          oponentTilesCount <- 4 - sum(oponentTiles)
          #cat("oponentTilesCount:", oponentTilesCount)
          
            if (oponentTilesCount == 0) {
              next
              
            } else if (oponentTilesCount == 1){
              
              #print("Pay rent for one T.")
              #print("player_Data:")
              #print(player_Data)
              
              player_Data$money <- player_Data$money - ( 25 * 4 ) # 2 *
              player_Data$debtCounter <- 25 * 4 # 2 *
              player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
            
            } else if (oponentTilesCount == 2){
              
              #print("Pay rent for two T.")
              #print("player_Data:")
              #print(player_Data)
              
              player_Data$money <- player_Data$money - ( 50 * 4 ) # 2 *
              player_Data$debtCounter <- 50 * 4 # 2 *
              player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
            
            } else if (oponentTilesCount == 3){
              
              #print("Pay rent for three T.")
              #print("player_Data:")
              #print(player_Data)
              
              player_Data$money <- player_Data$money - ( 100 * 4 ) # 2 *
              player_Data$debtCounter <- 100 * 4 # 2 *
              player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
            
            } else {
              
              #print("Pay rent for four T.")
              #print("player_Data:")
              #print(player_Data)
              
              player_Data$money <- player_Data$money - ( 200 * 4 ) # 2 *
              player_Data$debtCounter <- 200 * 4 # 2 *
              player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
            
          }
          
        } else if (gameBoard$tileType[player_Data$position] 
                 %in% c("E", "W")) {
        #print("YOU LANDED ON A UTILITY!")
        #print(gameBoard$tileType[player_Data$position] )
        
        oponentTiles <- gameBoard$ownedBy[c(17, 29)] %in% 
                c("!", "none", player_Data$name, player_Data$mortageStamp)
        #cat("oponentTiles:", oponentTiles)
        oponentTilesCount <- 2 - sum(oponentTiles)
        #cat("oponentTilesCount:", oponentTilesCount)
        
          if (oponentTilesCount == 0) {
            next
            
          } else if (oponentTilesCount == 1){
            
            #print("Pay rent for one utility.")
            #print("player_Data:")
            #print(player_Data)
            utilRent <- dice(1)*4
            #cat("rent:", utilRent)
            
            player_Data$money <- player_Data$money - ( utilRent * 4 ) # 2 *
            player_Data$debtCounter <- utilRent * 4 # 2 *
            player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
          
          } else if (oponentTilesCount == 2){
            
            #print("Pay rent for one utilities.")
            #print("player_Data:")
            #print(player_Data)
            utilRent <- dice(1)*10
            #cat("rent:", utilRent)
            
            player_Data$money <- player_Data$money - ( utilRent * 4 ) # 2 *
            player_Data$debtCounter <- utilRent * 4 # 2 *
            player_Data$debtorName <- gameBoard$ownedBy[player_Data$position]
          
          }
        
      } 
    }
    
    ## Player Buy Tiles, Graphics [START] ##
    buyOutput <- buyTileFunction(player_Data, ownedColors, currentAction)
    player_Data <- buyOutput[[1]]
    ownedColors <- buyOutput[[2]]
    currentAction <- buyOutput[[3]]
    
    while ( any(gameBoard$ownedBy == player_Data$mortageStamp) == T
            &
            any( player_Data$money > gameBoard$mortageIncome[gameBoard$ownedBy == player_Data$mortageStamp] ) == T
  ){

      mortageFlipOutput <- mortageFlipFunction(player_Data, 
                                               ownedColors,
                                               currentAction)

      player_Data <- mortageFlipOutput[[1]]
      ownedColors <- mortageFlipOutput[[2]]
      currentAction <- mortageFlipOutput[[3]]
    }

    ## Player Buy Tile, Graphics [END]    ##
      
    ## Player Sell Tile, Graphics [START] ##
    #print("player_Data$money")
    #print(player_Data$money)
    while (player_Data$money < 0 && gameOver == 0){ # while (player_Data$money < 0 && gameOver == 0) {

      sellOutput <- sellTileFunction(player_Data, 
                                     ownedColors,
                                     i,
                                     currentAction)

      player_Data <- sellOutput[[1]]
      ownedColors <- sellOutput[[2]]
      i <- sellOutput[[3]] # Trying to end game when Game Over.
      gameOver <- sellOutput[[4]]
      currentAction <- sellOutput[[5]]
      #print("gameOver, test:")
      #print(gameOver)
      
      if (player_Data$money < 0 && gameOver == 0){
        possibleSale <- which(gameBoard$ownedBy == player_Data$mortageStamp)
        possibleSalePrice <- gameBoard$tileCost[possibleSale]
        sellThis <- max(possibleSalePrice)
        sellThis <- which(gameBoard$tileCost == sellThis[1])
        sellThis <- sellThis[1]
        
        #print("sellThis:")
        #print(sellThis)
        
        if (is.na(sellThis)){
          gameOver <- 1
          n_rounds <- roundNr
  
          outputList <- list(
                             "n_rounds" = n_rounds, 
                             "player_Data" = player_Data,
                             "visited_tiles" = n_rounds,
                             "gameOver" = gameOver,
                             "cur_Action" = currentAction
                             )
          
          return(outputList) 
        }
        
        gameBoard$ownedBy[sellThis] <<- "none"
        player_Data$money <- player_Data$money + gameBoard$tileCost[sellThis]
        
        a <- masterTileList[sellThis]
        #print("a")
        #print(a)
        b_1 <- a[[1]][[1]]
        b_2 <- a[[1]][[2]]
        
        #print("b_1")
        #print(b_1)
        #print("b_2")
        #print(b_2)
        
        #cat("tileType:", gameBoard$tileType[sellThis])
        
        if (gameBoard$tileType[sellThis] %in% c("T1", "T2", "T3", "T4","W", "E")) {
          polygon(b_1, b_2, col = "white", lty = "dotted", lwd = 2)
        } else {
          polygon(b_1, b_2, col = gameBoard$tileType[sellThis], lty = "dotted", lwd = 2)
          # "pink"
        }
        
      } 
      
    }
    ## Player Sell Tile, Graphics [END]   ##
  }
    Sys.sleep(framePause)
    
    # clear Stat Graphics #
    polygon(
    c(0.68, 0.89, 0.89, 0.68), 
    c(0.95, 0.95, 0.725, 0.725),
    col = "white",
    border = "white"
    )
    
    polygon(
    c(1, 1.4, 1.4, 1), 
    c(0.95, 0.95, 0.725, 0.725),
    col = "white",
    border = "white"
    )

    # update player #
    #print("jail")
    #print(jail)
    if (sum(jail) == 0){
      
      movePlayer_Output <- movePlayer(player_Data)
      player_Data <- movePlayer_Output[[1]]
      
    } else {
      
      jailDice_1 <- dice(1)
      jailDice_2 <- dice(1)
      
      if (jailDice_1 == jailDice_2){
        
        movePlayer_Output <- movePlayer(player_Data)
        player_Data <- movePlayer_Output[[1]]
        currentAction <- "Action: Released from jail."
        text(
        1.2, 
        0.90,
        "Action: Released from jail.", 
        col = player_Data$color, 
        cex = 0.95, 
        )
        
      } else if (player_Data$money >= 500) { # 50
        
        player_Data$money <- player_Data$money - 500 # 50
        movePlayer_Output <- movePlayer(player_Data)
        player_Data <- movePlayer_Output[[1]]
        
        currentAction <- "Action: Paid bail."
        text(
        1.2, 
        0.90,
        "Action: Paid bail.", 
        col = player_Data$color, 
        cex = 0.95, 
        )
      }
    
    }
    
  n_rounds <- roundNr
  
  outputList <- list(
                     "n_rounds" = n_rounds, 
                     "player_Data" = player_Data,
                     "visited_tiles" = n_rounds,
                     "gameOver" = gameOver,
                     "cur_Action" = currentAction
                     )
  
  return(outputList) 
}

#----------------------------------------------------------------------------#

##------------------## Two player game loop - Function ##-------------------##
oneGameOfMonopolyFUNC <- function(ownedColors, gameBoard, framePause, n_loops, player_1, player_2, currentPlayer, gameOver, visited_tiles, jail){
  
    outputDescStats <- data.frame(
      "turnNr" = NA,
      "money" = NA,
      "currentPlayer" = NA,
      "action" = NA
    )

    while (gameOver == 0) {
      
      visited_tiles <- visited_tiles + 1
    
      if (visited_tiles %% 2 == 0) {
          #cat("jailTest:", jail)
          myRecord <- gameLoop(framePause, 
                               n_loops, 
                               player_Data = currentPlayer,
                               roundNr = visited_tiles,
                               monopoly = ownedColors,
                               cur_Action = currentAction,
                               jail = jail)
          player_2 <- myRecord$player_Data
          monopoly <- myRecord$monopoly
          
          player_2$money <- player_2$money + player_1$debtCounter
          player_2$debtCounter <- 0
          player_2$debtorName <- "none"
          
          currentPlayer <- player_1
          
          gameOver <- as.numeric(unlist(myRecord[4]))
          
          currentAction <- unlist(myRecord[5])

          turnStats <- visited_tiles
          cash <- player_2$money
        
      } else {
          #cat("jailTest:", jail)
          myRecord <- gameLoop(framePause, 
                               n_loops, 
                               player_Data = currentPlayer,
                               roundNr = visited_tiles,
                               monopoly = ownedColors,
                               jail = jail)
          player_1 <- myRecord$player_Data
          monopoly <- myRecord$monopoly
          
          player_1$money <- player_1$money + player_2$debtCounter
          player_1$debtCounter <- 0
          player_1$debtorName <- "none"
          
          currentPlayer <- player_2
          
          gameOver <- as.numeric(unlist(myRecord[4]))
          
          currentAction <- unlist(myRecord[5])

          turnStats <- visited_tiles
          cash <- player_1$money
          
      }
      
      outputDescStats <- rbind(outputDescStats, 
                               c( 
                                 unlist(turnStats), 
                                 unlist(cash),
                                 unlist(currentPlayer$name),
                                 unlist(currentAction)
                                 )
                               )
        
    }
  
    #if ( (as.numeric(unlist(max(outputDescStats$turnNr, na.rm = T))) ) %% 2 == 0){ # - 1
      #print("player 1 won the game!")
      #print(player_1$name)
    #} else {
      #print("player 2 won the game!")
      #print(player_2$name)
    #}
      
    myOutputList <- list(player_1, player_2, gameBoard, outputDescStats)
  
  dev.off() #
  return(myOutputList)
}
#----------------------------------------------------------------------------#
    
    multipleGamesResult[[length(multipleGamesResult)+1]] <- oneGameOfMonopolyFUNC(ownedColors, gameBoard, framePause, n_loops, player_1, player_2, currentPlayer, gameOver, visited_tiles, jail)
    #print(multipleGamesResult)
    cat("Game nr", i)
    print("GAME COMPLETED")
    
    Sys.sleep(10)
    }
  return(multipleGamesResult)
}
#----------------------------------------------------------------------------#

metaResult_B20 <- multipleGamesOfMonopolyFUNC(15) # metaResult
# metaResult
# print(metaResult)
```

Meta Statistics - Function

```{r}
metaStatisticsFunction <- function(metaResult){
  
  turnColl <- c()
  startingPlayers <- c()
  winners <- c()
  
  for (i in metaResult ){
    singleGame <- i
    gameStats <- singleGame[[4]]
    lastTurn <- max(as.numeric(unlist(gameStats$turnNr)), na.rm = T)
    #print(lastTurn)
    turnColl <- append(turnColl, lastTurn)
    
    firstPlayer <- gameStats$currentPlayer[2]
    #print(firstPlayer)
    startingPlayers <- append(startingPlayers, firstPlayer)
    
    player_1_stats <- singleGame[[1]]
    player_2_stats <- singleGame[[2]]
    
    if (player_1_stats$money < 0) {
      champion <- player_2_stats$name
      winners <- append(winners, champion)
    } else {
      champion <- player_1_stats$name
      winners <- append(winners, champion)
    }
    
  }
  #cat("turnColl:", turnColl)
  meanTurns <- mean(turnColl)
  #cat("meanTurns:", meanTurns)
  resultList <- list(turnColl, startingPlayers, winners)
  return(resultList)
}


#tot_res_vector_2 <- metaStatisticsFunction(metaResult_B1)

metaOutput_1 <- metaStatisticsFunction(metaResult_B1)
metaOutput_2 <- metaStatisticsFunction(metaResult_B2)
metaOutput_3 <- metaStatisticsFunction(metaResult_B3)
metaOutput_4 <- metaStatisticsFunction(metaResult_B4)
metaOutput_5 <- metaStatisticsFunction(metaResult_B5)
metaOutput_6 <- metaStatisticsFunction(metaResult_B6)
metaOutput_7 <- metaStatisticsFunction(metaResult_B7)
metaOutput_8 <- metaStatisticsFunction(metaResult_B8)
metaOutput_9 <- metaStatisticsFunction(metaResult_B9)
metaOutput_10 <- metaStatisticsFunction(metaResult_B10)

metaOutput_11 <- metaStatisticsFunction(metaResult_B11)
metaOutput_12 <- metaStatisticsFunction(metaResult_B12)
metaOutput_13 <- metaStatisticsFunction(metaResult_B13)
metaOutput_14 <- metaStatisticsFunction(metaResult_B14)
metaOutput_15 <- metaStatisticsFunction(metaResult_B15)
metaOutput_16 <- metaStatisticsFunction(metaResult_B16)
metaOutput_17 <- metaStatisticsFunction(metaResult_B17)
metaOutput_18 <- metaStatisticsFunction(metaResult_B18)
metaOutput_19 <- metaStatisticsFunction(metaResult_B19)
metaOutput_20 <- metaStatisticsFunction(metaResult_B20)

#metaOutput_21 <- metaStatisticsFunction(metaResult_B21)
#metaOutput_22 <- metaStatisticsFunction(metaResult_B22)
#metaOutput_23 <- metaStatisticsFunction(metaResult_B23)
#metaOutput_24 <- metaStatisticsFunction(metaResult_B24)
#metaOutput_25 <- metaStatisticsFunction(metaResult_B25)


tot_res_vector_2 <- c(metaOutput_1[[1]], metaOutput_2[[1]], metaOutput_3[[1]], metaOutput_4[[1]], metaOutput_5[[1]], metaOutput_6[[1]], metaOutput_7[[1]], metaOutput_8[[1]], metaOutput_9[[1]], metaOutput_10[[1]], metaOutput_11[[1]], metaOutput_12[[1]], metaOutput_13[[1]], metaOutput_14[[1]], metaOutput_15[[1]], metaOutput_16[[1]], metaOutput_17[[1]], metaOutput_18[[1]], metaOutput_19[[1]], metaOutput_20[[1]] ) #, metaOutput_21[[1]], metaOutput_22[[1]], metaOutput_23[[1]], metaOutput_24[[1]], metaOutput_25[[1]]
#)
print(tot_res_vector_2)

#print(metaOutput_2[[1]])
#print(metaOutput_2[[2]])
#print(metaOutput_2[[3]])

#hist(metaOutput_2[[1]], col = "blue")
#hist(tot_res_vector, col = "blue"#, xlim = c(0, 1100)#, 
#     ,breaks = 50
#     )
#hist(tot_res_vector, col = "blue", xlim = c(0, 1600)#, 
#     , breaks = 50
#     )

hist(tot_res_vector_2, col = "blue", xlim = c(0, 1600), 
     breaks = 50, main = "Histogram över kontrollgruppens 'rundor per parti'", xlab = "'rundor per parti'", ylab = "frekvens"
     )

plot.new()
#x11()

hist(tot_res_vector_2, col = "yellow", xlim = c(0, 1600), 
     breaks = 50, main = "Histogram över kontrollgruppens 'rundor per parti'", xlab = "'rundor per parti'", ylab = "densitet", probability = T)

lines(density(tot_res_vector_2), col="blue", lwd=2) # add a density estimate with defaults
lines(density(tot_res_vector_2, adjust=2), lty="dotted", col="darkgreen", lwd=2) 

length(tot_res_vector_2)
mean(tot_res_vector_2)
median(tot_res_vector_2)
```

Which Distribution? - Function

```{r}
install.packages("fitdistrplus")
install.packages("logspline")
library(fitdistrplus)
library(logspline)

descdist(tot_res_vector_2, discrete = T)

fit.nBinom <- fitdist(tot_res_vector_2, "nbinom")
plot(fit.nBinom)

fit.nBinom$aic

install.packages("gamlss")
install.packages("gamlss.dist")
install.packages("gamlss.add")
library(gamlss)
library(gamlss.dist)
library(gamlss.add)

fit <- fitDist(tot_res_vector_2, k = 2, type = "realplus", trace = FALSE, try.gamlss = TRUE)

summary(fit)

```
